
name: Main

on: [ push ]
#branch: main

jobs:

  test:
    name: Test
    strategy:
      matrix:
        platform: [ubuntu-latest] # [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x] # [10.x, 12.x, 14.x]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install requirements
      working-directory: ./app
      run: npm install
    - name: Run unit tests
      working-directory: ./app
      run: npm test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t myadd ./app
    - name: Push new image to dockerhub
      run: docker push theketrab/myadd


  # publish:
  #   needs: [build]
  #   steps:
  #   - uses: actions/checkout@v1
